package com.dok_si.tropicalfish.config;

import com.terraformersmc.modmenu.api.ConfigScreenFactory;
import com.terraformersmc.modmenu.api.ModMenuApi;
import com.dok_si.tropicalfish.TropicalFishCollection;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.text.Text;

public class ModMenuIntegration implements ModMenuApi {
    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return parent -> {
            YACLConfig config = YACLConfig.HANDLER.instance();

            return YetAnotherConfigLib.createBuilder()
                    .title(Text.translatable("config." + TropicalFishCollection.MOD_ID + ".title"))
                    .category(ConfigCategory.createBuilder()
                            .name(Text.translatable("config.tropicalfishcollection.category.general"))
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.only_show_collected"))
                                    .binding(false, () -> config.onlyShowCollected, val -> config.onlyShowCollected = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.darken_unsorted"))
                                    .binding(true, () -> config.darkenUnsorted, val -> config.darkenUnsorted = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.reset_on_death"))
                                    .binding(false, () -> config.resetOnDeath, val -> config.resetOnDeath = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .build())
                    .category(ConfigCategory.createBuilder()
                            .name(Text.translatable("config.tropicalfishcollection.category.display"))
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.grid_columns"))
                                    .binding(8, () -> config.gridColumns, val -> config.gridColumns = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 32).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.grid_rows"))
                                    .binding(8, () -> config.gridRows, val -> config.gridRows = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 32).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.max_bucket_icons"))
                                    .binding(256, () -> config.maxBucketIcons, val -> config.maxBucketIcons = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 1024).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.icon_scale"))
                                    .binding(20, () -> config.iconScale, val -> config.iconScale = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(10, 40).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.grid_offset_x"))
                                    .binding(0, () -> config.gridOffsetX, val -> config.gridOffsetX = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(-200, 200).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.grid_offset_y"))
                                    .binding(0, () -> config.gridOffsetY, val -> config.gridOffsetY = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(-200, 200).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.stats_offset_y"))
                                    .binding(15, () -> config.statsOffsetY, val -> config.statsOffsetY = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 100).step(1))
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.background_hex"))
                                    .binding("#000000", () -> config.backgroundHex, val -> config.backgroundHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.background_alpha"))
                                    .binding(204, () -> config.backgroundAlpha, val -> config.backgroundAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.check_hex"))
                                    .binding("#00FF00", () -> config.checkHex, val -> config.checkHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.check_alpha"))
                                    .binding(255, () -> config.checkAlpha, val -> config.checkAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.uncollected_hex"))
                                    .binding("#444444", () -> config.uncollectedHex, val -> config.uncollectedHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.uncollected_alpha"))
                                    .binding(255, () -> config.uncollectedAlpha, val -> config.uncollectedAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.cell_border_width"))
                                    .binding(0, () -> config.cellBorderWidth, val -> config.cellBorderWidth = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 5).step(1))
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.cell_border_hex"))
                                    .binding("#000000", () -> config.cellBorderHex, val -> config.cellBorderHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.cell_border_alpha"))
                                    .binding(255, () -> config.cellBorderAlpha, val -> config.cellBorderAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.stats_text_hex"))
                                    .binding("#FFAA00", () -> config.statsTextHex, val -> config.statsTextHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.stats_text_alpha"))
                                    .binding(255, () -> config.statsTextAlpha, val -> config.statsTextAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            // Цвет индикатора «собрана»
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_collected_hex"))
                                    .binding("#00FF00", () -> config.indicatorCollectedHex, val -> config.indicatorCollectedHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_collected_alpha"))
                                    .binding(255, () -> config.indicatorCollectedAlpha, val -> config.indicatorCollectedAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            // Цвет индикатора «не собрана»
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_uncollected_hex"))
                                    .binding("#FF0000", () -> config.indicatorUncollectedHex, val -> config.indicatorUncollectedHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_uncollected_alpha"))
                                    .binding(255, () -> config.indicatorUncollectedAlpha, val -> config.indicatorUncollectedAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            // Цвет индикатора «дубликат»
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_duplicate_hex"))
                                    .binding("#FFFF00", () -> config.indicatorDuplicateHex, val -> config.indicatorDuplicateHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_duplicate_alpha"))
                                    .binding(255, () -> config.indicatorDuplicateAlpha, val -> config.indicatorDuplicateAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.use_builtin_sound"))
                                    .binding(true, () -> config.useBuiltinSound, val -> config.useBuiltinSound = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.show_bucket_icon"))
                                    .binding(true, () -> config.showBucketIcon, val -> config.showBucketIcon = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.bucket_offset_x"))
                                    .binding(0, () -> config.bucketOffsetX, val -> config.bucketOffsetX = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(-25, 25).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.bucket_offset_y"))
                                    .binding(0, () -> config.bucketOffsetY, val -> config.bucketOffsetY = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(-25, 25).step(1))
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.show_sort_buttons"))
                                    .binding(true, () -> config.showSortButtons, val -> config.showSortButtons = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.indicator_size"))
                                    .binding(6, () -> config.indicatorSize, val -> config.indicatorSize = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(2, 14).step(1))
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.aggregate_notifications"))
                                    .binding(true, () -> config.aggregateNotifications, val -> config.aggregateNotifications = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<Boolean>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.highlight_uncollected_fish"))
                                    .binding(false, () -> config.highlightUncollectedFish, val -> config.highlightUncollectedFish = val)
                                    .controller(opt -> BooleanControllerBuilder.create(opt).yesNoFormatter())
                                    .build())
                            .option(Option.<String>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.highlight_color_hex"))
                                    .binding("#FFFF00", () -> config.highlightColorHex, val -> config.highlightColorHex = val)
                                    .controller(opt -> StringControllerBuilder.create(opt))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.highlight_color_alpha"))
                                    .binding(180, () -> config.highlightColorAlpha, val -> config.highlightColorAlpha = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(0, 255).step(1))
                                    .build())
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.highlight_range"))
                                    .binding(16, () -> config.highlightRange, val -> config.highlightRange = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(4, 64).step(1))
                                    .build())

                            .build())

                    .category(ConfigCategory.createBuilder()
                            .name(Text.translatable("config.tropicalfishcollection.category.tooltips"))
                            .option(Option.<YACLConfig.TooltipMode>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.tooltip_mode"))
                                    .binding(YACLConfig.TooltipMode.HOVER, () -> config.tooltipMode, val -> config.tooltipMode = val)
                                    .controller(opt -> EnumControllerBuilder.create(opt).enumClass(YACLConfig.TooltipMode.class))
                                    .build())
                            .build())
                    .category(ConfigCategory.createBuilder()
                            .name(Text.translatable("config.tropicalfishcollection.category.toasts"))
                            .option(Option.<Integer>createBuilder()
                                    .name(Text.translatable("config.tropicalfishcollection.toast_duration"))
                                    .binding(5000, () -> config.toastDurationMs, val -> config.toastDurationMs = val)
                                    .controller(opt -> IntegerSliderControllerBuilder.create(opt).range(1000, 15000).step(100))
                                    .build())
                            .build())

                    .save(() -> YACLConfig.HANDLER.save())
                    .build()
                    .generateScreen(parent);
        };
    }
}